### ISSUE TITLE
Technical Dimension: Overview - 4/10

### ISSUE THREAD

**Issue by elit0451** [cph-js284/UFOblog#2]
We consider your _“Overview”_ too vague by mentioning several aspects that you do not provide additional descriptions for. An example of this could be the fact that you are referring to mobile devices even though they are not mentioned throughout the blog post and the two databases chosen are not found in the mobile ecosystem. Additionally, various examples of suitable database engines are listed but no obvious explanation is stated as to why you narrow your scope to MongoDB and MySQL. Also, it would be interesting to see a reference to your old project work as it would provide a connection to your reasoning of the experiments conducted.

**Comment by cph-js284** [comment]
We might have made it more obvious that the example of mentioning mobile devices is only used as a vehicle for focusing on geodata.

With regards to narrowing it down to just the 2 databases that we focus on, we think the reason given “...Conducting experiments on all of these different types of databases is a task too large for the scope of this blog - so we have decided to narrow the scope to just experimenting using the MongoDB and MySql databases” is a good enough reason (confirmed by Kasper).

Regarding the reference, there actually is a one placed at the end of the blog. 

Considering this feedback we might shuffle a couple of things around to make things more obvious

This issue feedback was created by Yosuke, Benjamin and Jacob.
