### ISSUE TITLE
Technical Dimension: Reliable Data from Credible Sources - 7/10

### ISSUE THREAD

**Issue by davi7725** [cph-js284/UFOblog#3]
Here, the origin of the data sources you provide are fairly credible and reliable as they come from the official documentation of the technologies and data resources you’ve used. One thing we consider lacking is the in-depth explanation of why you chose the data you did. Also, on the exemplified queries you could have provided your own interpretation of the geospatial functions, while still referencing the official description for the database engine.

**Comment by cph-js284** [comment]
The reason we chose this particular query was that it is relevant for our blog and geodata.

“Also, on the exemplified queries you could have provided your own interpretation of the geospatial functions, while still referencing the official description for the database engine.”
TBH. not sure what the reviewer/feedbacker means by this statement. Besides we find our own interpretation irrelevant for the blog contents


This issue feedback was created by Yosuke, Benjamin and Jacob.
