### ISSUE TITLE
Technical Dimension: Design Constraints and Assumptions - 2/10

### ISSUE THREAD

**Issue by elit0451** [cph-js284/UFOblog#4]
You have omitted your justification on the design constraints of the selected databases. Even though you mentioned that indexes are important when executing performance testing, you failed to specify any assumptions for such a statement. We feel that more design alternatives could have been presented like with or without indexes, or ever different schemas.

**Comment by cph-js284** [comment]
We agree this part needs some scientific backing.
(based on this feedback we will update the blog with relevant links)

The design constraint are mainly there for reproducibility reasons, we feel that it is important that the reader has a chance to reproduce the experiment. Presenting the schemas without indexes just to compare is outside the scope of this blog.

This issue feedback was created by Yosuke, Benjamin and Jacob.
