### ISSUE TITLE
Technical Dimension: Theoretical Explanations - 2/10

### ISSUE THREAD

**Issue by davi7725** [cph-js284/UFOblog#5]
Throughout the blogpost, the theoretical explanations could have been more elaborate. Mostly in the part where you exemplify the two queries used, it would have been good to see detailed explanations about the geospatial function you use in both databases, as well as, an attempt to argue why there is such a performance difference between the two. Furthermore, for the general audience, an explanation for your schema design choice could have been a good technical addition.

**Comment by cph-js284** [comment]
We agree with most of this

a detailed walkthrough of the queries used, is beyond the scope of this blog, which is mainly focused on the comparison between  mysql and mongodb geodata usage

however, we have updated the blog with a small description of the relevant geospatial functions used in the queries.


This issue feedback was created by Yosuke, Benjamin and Jacob.
