### ISSUE TITLE
Technical Dimension: Design Criteria, Sample Calculations and Simulations - 6/10

### ISSUE THREAD

**Issue by elit0451** [cph-js284/UFOblog#6]
There was a good structure of the data used when taking measurements which helps to demonstrate your effort through the usage of graphs. It is excellent that you provide such detailed documentation to the reader that can draw their own conclusions from that data. Regarding design criteria, however, you failed to provide any thoughts and argumentation on the schemas designed.

**Comment by cph-js284** [comment]
We agree with this and have updated the blog accordingly, with the relevant information.

This issue feedback was created by Yosuke, Benjamin and Jacob.
