### ISSUE TITLE
Technical Dimension: Previous Work/Future Work - 3/10

### ISSUE THREAD

**Issue by davi7725** [cph-js284/UFOblog#7]
While you have mentioned the usage of data from a previous project, you missed the chance for elaborating on the description of it. This would for sure make the reader more comfortable with the schemas presented and the reasoning for your design choices.
The _“Perspective”_ section feels too short and does not really entail any thoughts on why your results would have a significant impact on future implementations. These could also include more general thoughts on how different types of data need to be taken into consideration when choosing a suitable database.

**Comment by cph-js284** [comment]
We feel that at this point we have adequately addressed the reason for not spending more time/lines on design decisions. We agree that the perspective section should be more elaborate and have updated this section.


This issue feedback was created by Yosuke, Benjamin and Jacob.
